### DISCUSSION TITLE
How to enable resource management in kurtosis with kubernetes backend?

### DISCUSSION THREAD

**Discussion by barnabasbusa** [kurtosis-tech/kurtosis#952] [Q&A] [answered]
Resource management is a huge benefit of kubernetes. Automatic up/down scaling based on current CPU/RAM usage is one of the main reason people choose to go with kubernetes the first place. 

Is it already possible to configure kurtosis with specific resource requests and limits for specific pods? 

[example](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/): 
```yaml
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

If its not yet possible, it would be great to be able to individually limit/request resources based on the different client combination you are running. E.g you might want to give more RAM but less CPU for a `besu` node. 

Without requests/limits, autoscaling in the cloud is not going to be possible. 

While talking about resource limits, its also worth mentioning that [docker](https://docs.docker.com/config/containers/resource_constraints/) has similar ways to limit specific containers to specific amount of resources. So this could be handled at the same time, using the same flags configured in starlark.
