### ISSUE TITLE
Support `DOCKER_HOST` environment variable

### ISSUE THREAD

**Issue by carrion256** [kurtosis-tech/kurtosis#1072]
### Background & motivation

Most applications that integrate with Docker support the [DOCKER_HOST](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables) environment variable. This allows for a unified approach to connecting to the docker socket. 

In some cases, users might use something like Podman or other engines which shim a lot of their features over a Docker API.
In other cases, users might expose a non-root socket for docker, [like this nixos home-manager interface](https://nixos.wiki/wiki/Docker#Rootless_docker), which exposes the socket as `unix:///run/user/1000/docker.sock`.  

Anyhow, supporting this flag would allow Kurtosis to support Podman & Friends **mostly for free**. 

### Desired behaviour

Docker engine should respect the `DOCKER_HOST` environment variable, and allow a config for it in the Kurtosis cfg file.

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

**Comment by carrion256** [comment]
In the meantime, just patch the [constant](https://github.com/kurtosis-tech/kurtosis/blob/752d6c530d96c72049c5dc33f2ff11e70f18c02d/container-engine-lib/lib/backend_impls/docker/docker_kurtosis_backend/consts/consts.go#L22) and rebuild Kurtosis, as I can't see anywhere this is configurable.

**Comment by adschwartz** [comment]
@dndll Thank you for submitting this issue. We're having a look and will get back soon!

**Comment by mieubrisse** [comment]
Thanks for filing this @dndll ; makes a ton of sense! Suppose that Docker clusters defined in the Kurtosis config file had a `socket` config file, analogous to the DOCKER_HOST variable; so something like this:
```
clusters:
  podman:
    type: docker    # Sets the cluster type to use the Docker backend
    socket: unix:///var/run/podman.sock
```
Would that solve your usecase?

**Comment by carrion256** [comment]
> Thanks for filing this @dndll ; makes a ton of sense! Suppose that Docker clusters defined in the Kurtosis config file had a `socket` config file, analogous to the DOCKER_HOST variable; so something like this:
> 
> ```
> clusters:
>   podman:
>     type: docker    # Sets the cluster type to use the Docker backend
>     socket: unix:///var/run/podman.sock
> ```
> 
> Would that solve your usecase?

Thanks for getting back so quickly @mieubrisse - This seems really useful actually, so that means you can use many different engines alongside kurtosis? I can for sure see additional use cases on top of this, like profiling various engines.

**Comment by mieubrisse** [comment]
Full transparency, we only test with Docker and Kubernetes backends. If Podman has a Docker API endpoint shim though, I'd hope ( 🤞 ) that the Docker client we're using internally would Just Work on Podman (and I don't think this is far-fetched, since Podman focuses heavily on easy conversion from Docker).

Though I just realized you might be asking, "can I have my Kurtosis CLI linked up to multiple backends at the same time?" - if so, yes, Kurtosis can be aware of multiple backend clusters at the same time which can be accessed through the `kurtosis cluster` family of command (the default Kurtosis config has `docker` and `minikube` out of the box). Example config:

```
config-version: 2
should-send-metrics: true
kurtosis-clusters:
  docker:
    type: "docker"
  minikube:
    type: "kubernetes"
    config:
      storage-class: "standard"
      enclave-size-in-megabytes: 10
  cloud:
    type: "kubernetes"
    config:
      storage-class: "standard"
      enclave-size-in-megabytes: 10
```

(more details on https://docs.kurtosis.com/config-path/ )

Re. implementing the above, I think this will be several hours of work (we need to build some extra deserializing into the config); let me check with @tedim52 about his bandwidth.

@tedim52 , the work I think we'd need:

1. add a new `v3` version of the Kurtosis CLI config, that has polymorphic deserialization for cluster blocks to determine between Kubernetes and Docker (right now we assume Kubernetes).
2. build the migrator from v2 -> v3 so users' current configs don't break
3. pipe the config value down to the Docker client so that we're no longer using hardcoded `/var/run/docker.sock`
