### ISSUE TITLE
Kurtosis cluster name not matching kubernetes cluster name - guardrails are required

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1080]
### What's your CLI version?

0.81.5

### Description & steps to reproduce

Lets assume you have access to 2 clusters from your computer. 
`Kubernetes ClusterA`
`Kubernetes ClusterB`

On your kurtosis config you configure that you would like to work in `ClusterA`.
However, during the day you have some tasks that require you to context switch to `ClusterB`. Then later on you run a kurtosis engine restart command, and `ClusterB` will start running your engine, and all kurtosis tasks will be scheduled on `ClusterB`.

### Desired behavior

It would be good to require kube context name to match the kubernetes name in kurtosis config.

E.g: 
```yaml
config-version: 2
should-send-metrics: true
kurtosis-clusters:
  docker:
    type: "docker"
  minikube:
    type: "kubernetes"
    config:
      kubernetes-cluster-name: "minikube"
      storage-class: "standard"
      enclave-size-in-megabytes: 10
  cloud:
    type: "kubernetes"
    config:
      kubernetes-cluster-name: ClusterA (This field should/must match the kube config context name) 
      storage-class: "standard"
      enclave-size-in-megabytes: 10
```

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.
