### ISSUE TITLE
investigate the interplay between cluster set & kubectl current-context when multiple clusters are configured

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1554]
### What's your CLI version?

0.84.3

### Description & steps to reproduce

```
config-version: 2
should-send-metrics: true
kurtosis-clusters:
  cloud:
    type: kubernetes
    config:
      kubernetes-cluster-name: arn:aws:eks:us-east-2:258623609258:cluster/gyani-cluster
      storage-class: standard
      enclave-size-in-megabytes: 10
  docker:
    type: docker
  minikube:
    type: kubernetes
    config:
      kubernetes-cluster-name: minikube
      storage-class: standard
      enclave-size-in-megabytes: 10
```

I have a kurtosis config that looks like ^; earlier it had a digital ocean cluster as well.  The gyani-cluster has no node groups but still things are spinning up; if I stop the gateway it prints that its stopping connections with a digital ocean url; so cloud is actually launching things in the digital ocean cluster. The ./.kube/config file doesn't mix the two; the gyani-cluster has aws urls. So I am confused whats' going on.

Seems like my current-context in k8s is set to the digital ocean cluster & Kurtosis seems to go off of that instead of kurtosis cluster set. Changing current-context on the kube config is making kurtosis engine restart fail as expected (no node groups on aws)

### Desired behavior

Kurtosis uses the value in `kurtosis cluster get` instead of the current context.

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

CLI: the Command Line Interface
