### ISSUE TITLE
Allow to use yaml files as args-file

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1600]
### Background & motivation

It would be great to be able to use YAML files as well as JSON when passing a arg file to kurtosis.

### Desired behaviour

While this is cool: 
```json
{
  "participants": [
      {
        "el_client_type": "geth",
        "cl_client_type": "lodestar",
        "count": 3
      }
  ],
  "network_params": {
      "deneb_fork_epoch": 3,
      "seconds_per_slot": 3,
      "genesis_delay": 300
  },
  "additional_services": [
      "el_forkmon",
      "dora"
  ],
  "snooper_enabled": true
}
```

I think this would be even nicer:
```yaml
participants:
  - el_client_type: geth
    cl_client_type: lodestar
    count: 3
  - el_client_type: nethermind
    cl_client_type: lodestar
    count: 3
network_params: 
  deneb_fork_epoch: 3
  seconds_per_slot: 3
  genesis_delay: 300
additional_services:
  - el_forkmon
  - dora
snooper_enabled: true
```

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

CLI: the Command Line Interface
