### ISSUE TITLE
Add logging to kurtosis cloud

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#1652]
### Background & motivation

While launching a new enclave, I see no logs, so no progression on whether the enclave is running or not properly.
Example: 
![Screenshot 2023-10-30 at 16 21 46](https://github.com/kurtosis-tech/kurtosis/assets/21987084/b82c8cd8-fcbd-499a-9ac0-e2e3ebb5c491)

### Desired behaviour

I would like to see live logs of the enclave. 

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by tedim52** [comment]
Hey @barnabasbusa ! Thanks for filing this. This is actually unexpected - when you click the `Run` button, you should be sent straight to a screen that displays incoming logs from the enclave. If you're not seeing that, that's a bug we need to address! 

Just verifying, is it the case that everytime you click the `Run` button, you don't get routed to an "enclave logs" screen?

**Comment by barnabasbusa** [comment]
Happened 3 times already on safari: 

Config: 
```yaml
participants:
  - el_client_type: geth
    cl_client_type: lighthouse
  - el_client_type: besu
    cl_client_type: prysm
network_params: 
  deneb_fork_epoch: 3
  seconds_per_slot: 3
additional_services:
  - el_forkmon
  - dora
  - prometheus_grafana
mev_type: full
```
