### ISSUE TITLE
Expose the files artifacts consumed by a service in `service inspect` and Service Overview screen in the GUI

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1777]
### Background & motivation

We can't currently see which files artifacts a service is using, nor where they're mounted.

### Desired behaviour

`service inspect` also returns the mountpoints of the files artifacts consumed by the service like so:
```
Name: postgres
UUID: 79b8ebba4160
Status: RUNNING
Image: postgres:alpine
Ports:
  postgresql: 5432/tcp -> postgresql://127.0.0.1:32828
ENTRYPOINT:
  docker-entrypoint.sh
CMD:
  postgres
ENV:
  LANG: en_US.utf8
  POSTGRES_PASSWORD: MyPassword1!
  POSTGRES_DB: postgres
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PG_SHA256: df9e823eb22330444e1d48e52cc65135a652a6fdb3ce325e3f08549339f51b99
  POSTGRES_USER: postgres
  PG_MAJOR: 16
  PG_VERSION: 16.0
  DOCKER_PG_LLVM_DEPS: llvm15-dev 		clang15
  PGDATA: /data/
Files:
  /data: my-files-artifact
  /somewhere-else: some-other-files-artifact
```

This information is also displayed in the Service Overview in the GUI, with links to the files artifact.

This will require upgrading the backend to store the files artifacts that a service uses (which we don't currently do)

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

CLI: the Command Line Interface
