### ISSUE TITLE
add ability to update the running image, parameters, and configuration of a given service

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#2057]
### Background & motivation

https://github.com/kurtosis-tech/ethereum-package/issues/465
https://github.com/kurtosis-tech/ethereum-package/issues/458

There have been some requests from users of the Ethereum Package to change a service in the network when it comes to its underlying image or arguments so that they don't have to recreate the testnet

### Desired behaviour

An `update_service` api that allows you to change image or other arguments of a given service

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by h4ck3rk3y** [comment]
idempotent runs might solve for this!

**Comment by mieubrisse** [comment]
Hey @h4ck3rk3y ! yep, I think enclave updating (formerly known as idempotent runs 😆 ) would solve for this - just re-throw an updated configuration at the enclave

**Comment by h4ck3rk3y** [comment]
Yep! idempotent runs / updates do solve this. Everything but the affected instructions get skipped.

**Comment by h4ck3rk3y** [comment]
Waiting for @barnabasbusa to confirm if this is enough for now; will close this if so

**Comment by h4ck3rk3y** [comment]
Currently proposed workflow is arg tweaking and re-running against the same enclave

```
participants:
  - el_client_type: geth
    cl_client_type: lighthouse
  - el_client_type: geth
    cl_client_type: lighthouse
  - el_client_type: geth
    cl_client_type: lighthouse
    el_client_image: "ethereum/client-go:v1.13.10"
```

Changing the 10 to 11 and back to 10, seems to work on my machine
