### ISSUE TITLE
Node selector can't contain "/" due to conflicting label rules

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#2139]
### What's your CLI version?

0.86.17

### Description & steps to reproduce

Example config:
```yaml
participants:
  - el_client_type: geth
    el_client_image: ethpandaops/geth:master
    cl_client_type: teku
    cl_client_image: ethpandaops/teku:master
  - el_client_type: geth
    el_client_image: ethpandaops/geth:master
    cl_client_type: teku
    cl_client_image: ethpandaops/teku:master
    node_selectors: {
        "k3s.io/hostname": asrock-berlin-07
    }
additional_services:
  - dora
snooper_enabled: true
persistent: true
global_node_selectors: {
    "k3s.io/hostname": asrock-berlin-03
}
```

Error message:
```sh
There was an error interpreting Starlark code 
Evaluation error: Cannot construct 'ServiceConfig' from the provided arguments.
        Caused by: The following argument(s) could not be parsed or did not pass validation: {"node_selectors":"An error occurred validating service config labels 'map[k3s.io/hostname:asrock-berlin-07]'\n\tCaused by: Invalid service config label key 'k3s.io/hostname'\n --- at /home/circleci/project/container-engine-lib/lib/backend_interface/objects/service/service_config_validators.go:16 (ValidateServiceConfigLabels) ---\nCaused by: User custom label key 'k3s.io/hostname' is not valid\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/object_attributes_provider/docker_label_key/docker_label_key.go:48 (ValidateUserCustomLabelKey) ---\nCaused by: Label key string 'com.kurtosistech.custom.k3s.io/hostname' doesn't match Docker label key regex '^[a-z0-9-._]+$'\n --- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/object_attributes_provider/docker_label_key/docker_label_key.go:80 (validate) ---"}
        at [github.com/kurtosis-tech/ethereum-package/main.star:89:55]: run
        at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:439:42]: launch_participant_network
        at [github.com/kurtosis-tech/ethereum-package/src/el/geth/geth_launcher.star:132:24]: launch
        at [github.com/kurtosis-tech/ethereum-package/src/el/geth/geth_launcher.star:372:25]: get_config
        at [0:0]: ServiceConfig

Error encountered running Starlark code.
```

This is caused by kurtosis trying to create a custom label for the node selector, and finds that `/` character is invalid.

Workaround, ignore all node selectors from custom fields. As these will 99% of the time include `/` characters. 

### Desired behavior

Node selector should be applied to specified service. 

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

CLI: the Command Line Interface
