### ISSUE TITLE
FR: Make pull through docker hub cache configurable during runtime

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#2384]
### Background & motivation

It's fairly easy to overload a network when there are multiple users trying to fetch gigabytes worth of docker images all at the same time. It would be great if with an additional flag, a local pull through cache could be configured, so that all images could be cached for the next user. This feature would make sense in dense situations, where there are dozens of people trying to fetch tens of different docker images.
This feature would enable accessing private repositories without needing to specify username/password during runtime.

Anyone can super quickly spin up a pull through cache using: https://docs.docker.com/docker-hub/mirror/

Lets assume your pull through cache is configured to be hosted at: http://192.168.1.100:5000
Right now it works with:
```yaml
participants:
  - el_type: geth
    el_image: 192.168.1.100:5000/ethpandaops/geth:master
    cl_type: lighthouse
    cl_image: 192.168.1.100:5000/ethpandaops/lighthouse:unstable
    count: 2
```
However, ideally you should be able to cache all kurtosis images too.

### Desired behaviour

It would be great if there could be an additional flag like `--private-repository <url>` during `kurtosis run` command that would enable one to specify a private repository/pull through cache. This would enable all commands to go via this cache, and speed up the spin up time significantly, without needing to specify the cache's location in each image individually. 

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface
