### ISSUE TITLE
FR: Be able to define kurtosis flags in an argument file

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#2428]
### Background & motivation

It would be great to have a single document that defines all the runtime parameters of a kurtosis run.

For example, right now we have to pass all the runtime arguments in the same command, and if we forget to run it, we might have a different enclave name, or different pull policy than expected.

### Desired behaviour

I would like to be able to pass the kurtosis runtime parameters in the same argument file that I pass for a package.
This should be parsed, and if someone runs the same yaml file, they should get exactly the same runtime. 

For example:

Current setup:
```yaml
participants:
  - count: 2
network_params:  
  preset: minimal
additional_services: 
  - dora
  - tx_spammer

tx_spammer_params:
  tx_spammer_extra_args: ["--accounts=1", "--txcount=1"]
```
Runtime:
`kurtosis run github.com/kurtosis-tech/ethereum-package@bbusa/test1 --args-file <url> --verbosity detailed --image-download always --enclave testing ....` (potentially any of the kurtosis runtime variables)

Future setup:
```yaml
kurtosis:
  url: github.com/kurtosis-tech/ethereum-package
    branch: bbusa/test1
  verbosity: detailed
  image-download: always
  enclave: testing
  args-file: .
participants:
  - el_type: nethermind
    cl_type: lighthouse
network_params:  
  preset: minimal
additional_services: 
  - dora
  - tx_spammer

tx_spammer_params:
  tx_spammer_extra_args: ["--accounts=1", "--txcount=1"]
```
Runtime: `kurtosis run`

This should ideally work in kurtosis cloud too. 

### How important is this to you?

Nice to have; this feature would make using Kurtosis more enjoyable.

### What area of the product does this pertain to?

CLI: the Command Line Interface
