### ISSUE TITLE
Run kurtosis on k8s on GCP

### ISSUE THREAD

**Issue by nidhi-singh02** [kurtosis-tech/kurtosis#2451]
### Background & motivation

Wish to run kurtosis on k8s(GKE) on Google Cloud Platform. I don't see any `storage-class` in the documentation here  https://docs.kurtosis.com/k8s/#iii-add-your-cluster-information-to-kurtosis-configyml. 

### Desired behaviour

Need to know what value should I pass to `storage-class`

### How important is this to you?

Critical; Kurtosis is unusable for me without it.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by h4ck3rk3y** [comment]
Hey @nidhi-singh02 

Can you run `kubectl get storageclass`

I believe the value for gcp should be `standard`. That should also show up in the output of the command

**Comment by nidhi-singh02** [comment]
Hi, 
I ran the above command, in that I could see `standard` as well @h4ck3rk3y.

let me try running with `standard` storage class.

**Comment by nidhi-singh02** [comment]
I have an update, it works on GCP with storage class `standard`. I tried running `minikube` profile and it works fine on GCP as I think it picks the cluster name from the context and minikube already has storage-class as standard. Could we please update the document for GCP, I am happy to raise the PR if we wish to update the doc :)


```
config-version: 2
should-send-metrics: true
kurtosis-clusters:
  docker:
    type: "docker"
  minikube:
    type: "kubernetes"
    config:
      kubernetes-cluster-name: "minikube"
      storage-class: "standard"
      enclave-size-in-megabytes: 10
```
