### ISSUE TITLE
Support annotations in volumeClaimTemplate for broader cloud provider compatibility

### ISSUE THREAD

**Issue by TobiWo** [kurtosis-tech/kurtosis#2710]
## Overview

Currently, a user can only define a storage class name for dynamic storage provisioning. While this covers major cloud providers, it's insufficient for all use cases. This limitation can be addressed by adding support for `volumeClaimTemplate` annotations, which are often used for provider-specific resource settings.

## Technical details

The standard Kubernetes resource definition for volume claim templates supports annotations, which don't appear to be exposed in the current Kurtosis implementation:

```
volumeClaimTemplates:
    - metadata:
        name: "my-storage-name"
        labels:
          my-label: "label"
        annotations:
          my-storage-setting-one: "setting-one"
          my-storage-setting-two: "setting-two"
          my-other-annotation: "annotation"
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "storage-class-name"
        resources:
          requests:
            storage: "10Gi"
```

It's important that the implementation supports multiple annotations simultaneously (as a dictionary/map structure) to accommodate different use cases across cloud providers and storage systems.

### Desired behaviour

This enhancement would allow users to configure storage-specific parameters required by providers beyond the major ones (AWS, GCP, Azure), thereby increasing Kurtosis adoption across diverse cloud environments. Additionally, it would enable users with custom storage solutions or specific performance requirements to fine-tune their storage configurations without workarounds, making Kurtosis more flexible and universally applicable across the Kubernetes ecosystem.

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface
